# -*- coding: utf-8 -*-
"""01_EDA_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOxhc7YMYOqzDDIkKEdMMZLyUB-QinQg
"""

# 한글 깨짐 방지
!pip install koreanize-matplotlib

# 필요 라이브러리 import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# csv 파일 불러오고 데이터 특성 확인
health_data = pd.read_csv("/content/smoking_health_data.csv")
health_data.columns = [c.strip() for c in health_data.columns]    # 컬럼명 앞뒤 공백 제거
health_data = health_data[["ID", "나이", "키(cm)", "몸무게(kg)", "BMI", "시력", "충치", "공복 혈당", "혈압", "중성 지방", "혈청 크레아티닌", "콜레스테롤", "고밀도지단백", "저밀도지단백", "헤모글로빈", "요 단백", "간 효소율", "label"]].copy()
health_data.columns = ["raw_id", "age", "height_cm", "weight_kg", "bmi", "sight", "cavity", "fasting_blood_sugar", "bp", "triglyceride", "creatinine", "cholesterol", "hdl", "ldl", "hemoglobin", "proteinuria", "liver_enzyme_level", "label"]

print(health_data.shape)    # (7000, 18)
print(health_data.info())
print(health_data.describe())    # 결측치 존재: 시력, 공복 혈당, 혈압, 중성 지방    # 도메인적 결측치(0이 아니어야 하는데 0인 경우) 없음  # 편차 큼: 저밀도지단백, 중성 지방, 시력

# 범주형 데이터 확인
print("\n충치 범주: ")
display(health_data["cavity"].unique())

print("\n요 단백 범주: ")
display(health_data["proteinuria"].unique())

# 파생 변수 생성
health_data['Smoker'] = health_data['label'].replace({0: '비흡연자', 1: '흡연자'})

# 파생변수 변환 함수 파일 불러오기
import sys
sys.path.append("/content/feature_engineering.py")

from feature_engineering import add_features

# 파생변수 추가 확인
health_data = add_features(health_data)
health_data.head()

# 시각화 파일 불러오기
sys.path.append("/content/viz.py")
from viz import boxplt_with_mean, hist_one_feature, all_feature_plot

# 시력 데이터 전처리1 - 데이터 분포 확인
order = ["30대 미만", "30~50대", "50~70대", "70대 이상"]

boxplt_with_mean(health_data, "age_section", "sight", order, "연령대별 시력 데이터", outlier_rule={"value": 9.0, "label": "시력 이상치 기준(>9.0)"})

# 시력 데이터 전처리2 - “시력은 연령에 따라 구조적 차이가 존재하므로, 전체 최빈값 대체 대신 연령대별 평균값으로 결측치를 보완"
health_data["sight"] = (
    health_data
        .groupby("age_section")["sight"]
        .transform(lambda sight: sight.fillna(sight.mean()))
)

# 확인
health_data['sight'].isna().sum() # np.int64(0) -> 결측치 처리 완료

# 시력 데이터 전처리3 - "아무리 눈이 좋은 몽골인이어도 9가 최대이기 때문에 9를 넘으면 이상치로 판단하고 이상치를 제외한 가장 높은 수치로 변환"
max_sight = health_data.loc[health_data["sight"] <= 9, "sight"].max()
health_data.loc[health_data["sight"] > 9, "sight"] = max_sight

# 시력 데이터 전처리4 - 전처리 결과 확인
order = ["30대 미만", "30~50대", "50~70대", "70대 이상"]

boxplt_with_mean(health_data, "age_section", "sight", order, "연령대별 시력 데이터", outlier_rule={"value": 9.0, "label": "시력 이상치 기준(>9.0)"})

# 공복 혈당 전처리1 - 분포 확인
hist_one_feature(health_data, "fasting_blood_sugar", "공복 혈당 데이터 분포", bins=30, upper=200)

# 공복 혈당 전처리2 - 결측치 처리: "오른쪽으로 꼬리가 긴 치우친 분포이기 때문에 평균값보다 중앙값이 적절"
median_fbs = health_data["fasting_blood_sugar"].median()

health_data["fasting_blood_sugar"] = (
    health_data["fasting_blood_sugar"]
    .fillna(median_fbs)
)

health_data['sight'].isna().sum() # np.int64(0): 결측치 처리 완료

# 공복 혈당 이상치 처리 - 정맥 혈당 검사의 일반적인 검출 범위: 통상적으로 10 mg/dL ~ 500 mg/dL 이상의 범위를 측정
# 실제 문제가 있는 의미 있는 데이터일 수 있으니 유지

# 혈압 전처리 1 - bmi에 따른 분포 확인
order = ["저체중", "정상", "과체중", "비만"]

boxplt_with_mean(health_data, "bmi_level", "bp", order, "BMI level에 따른 혈압 데이터")

# 혈압 전처리2 - 결측치 처리: 이상치가 많아서 평균으로 대체하면 왜곡 가능. 중앙값으로 대체. 이상치는 의미 있는 데이터라 판단하여 유지.
health_data['bp'] = (
    health_data
        .groupby('bmi_level')['bp']
        .transform(lambda b: b.fillna(b.median()))
)
health_data['bp'].isna().sum() # np.int64(0): 결측치 처리 완료

# 중성 지방 전처리1 - bmi에 따른 분포 확인
order = ["저체중", "정상", "과체중", "비만"]

boxplt_with_mean(health_data, "bmi_level", "triglyceride", order, "BMI level에 따른 중성 지방 분포", outlier_rule={"value": 500, "label": "급성 췌장염 발생 위험!"})

# 중성 지방 전처리2 - 결측치 처리: "그룹별 중앙값으로 대체"
health_data['triglyceride'] = (
    health_data
        .groupby('bmi_level')['triglyceride']
        .transform(lambda t: t.fillna(t.median()))
)
health_data['triglyceride'].isna().sum()

# LDL 전처리 - 이상치 처리: "400을 초과하는 수치는 신뢰도가 떨어지기 때문에 400 이하의 데이터 값 중 가장 큰 값으로 대체"
max_ldl = health_data.loc[health_data["ldl"] <= 400, "ldl"].max()
health_data.loc[health_data["ldl"] > 400, "ldl"] = max_ldl

health_data.isna().sum()

# [전처리 step2] - 로그 변환 필요 유무 확인(왜도 파악)

feature_list = ["bmi", "sight", "fasting_blood_sugar", "bp", "triglyceride", "creatinine", "cholesterol", "hdl", "ldl", "hemoglobin", "liver_enzyme_level"]

all_feature_plot(health_data, feature_list)

# 왜도 >= 1.5 feature들 로그변환
health_data["sight_log"] = np.log1p(health_data["sight"])
health_data["fbs_log"] = np.log1p(health_data["fasting_blood_sugar"])
health_data["creatinine_log"] = np.log1p(health_data["creatinine"])
health_data["lel_log"] = np.log1p(health_data["liver_enzyme_level"])

# 로그 변환 후 확인
feature_list = ["bmi", "sight_log", "fbs_log", "bp", "triglyceride", "creatinine_log", "cholesterol", "ldl", "hdl", "hemoglobin", "lel_log"]

all_feature_plot(health_data, feature_list)

# csv 파일 저장 전 마무리 체크
display(health_data.head(3))
print("\n전처리 후 info:")
health_data.info()

print("\n전처리 후 결측치 점검:")
print(health_data.isna().sum())

print("\n전처리 후 describe:")
health_data.describe()

# csv 파일 저장
health_data.to_csv("smoking_health_data_preprocessed_v1.csv", index=False, encoding="utf-8")

